# Generated by Django 3.0.4 on 2020-10-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.TextField()),
                ('a2', models.TextField()),
                ('a3', models.TextField()),
            ],
        ),
    ]
