# Generated by Django 3.0.4 on 2020-10-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='a4',
            field=models.FileField(default='resume.pdf', upload_to='pdf'),
        ),
    ]
