# Generated by Django 3.0.4 on 2020-10-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_resume_a4'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(max_length=50)),
                ('s2', models.CharField(max_length=50)),
                ('s3', models.CharField(max_length=50)),
                ('s4', models.CharField(max_length=50)),
                ('s5', models.CharField(max_length=50)),
                ('s6', models.CharField(max_length=50)),
                ('s7', models.CharField(max_length=50)),
            ],
        ),
    ]
