# Generated by Django 3.0.4 on 2020-10-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_myskills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MySkills',
            new_name='MySkill',
        ),
    ]
