# Generated by Django 3.0.4 on 2020-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_auto_20201011_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myskill',
            name='s6',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='s7',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='s8',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
