# Generated by Django 3.0.4 on 2020-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20201011_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myskill',
            name='s8',
        ),
        migrations.AlterField(
            model_name='myskill',
            name='s6',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='s7',
            field=models.CharField(max_length=50),
        ),
    ]
