# Generated by Django 3.0.4 on 2020-10-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_myproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myskill',
            old_name='s1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='myskill',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='myskill',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='myskill',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='myskill',
            name='s5',
        ),
        migrations.RemoveField(
            model_name='myskill',
            name='s6',
        ),
        migrations.RemoveField(
            model_name='myskill',
            name='s7',
        ),
    ]
