# Generated by Django 3.0.4 on 2020-10-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_auto_20201014_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='a1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='a3',
        ),
    ]
