# Generated by Django 3.0.4 on 2020-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_auto_20201014_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='a4',
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.FileField(default='resume.pdf', upload_to='pdf'),
        ),
    ]
